/** Figma-exported image assets. Valid for 7 days from export date. */
export const assets = {
  logomark:     '/Images/Okta_Logomark.svg',
  logomarkDark: '/Images/Okta_Logomark_Dark_Edition.svg',
  sun:          '/Images/Sun.svg',
  moon:         '/Images/Moon.svg',
  heroImage:    '/Images/Hero_Image.png',
  leftPreview:  '/Images/left-top-preview.png',
  rightPreview: '/Images/right-top-preview.png',
  leftPreviewMobile: '/Images/left-top-preview-mobile.png',
  rightPreviewMobile: '/Images/right-top-preview-mobile.png',
  chevronRight: '/Images/chevron-right.svg',
  iconMinus:    '/Images/IconMinus.svg',
  iconPlus:     '/Images/IconPlus.svg',
  circle:       '/Images/Circle.svg',
  arrowLeft:    '/Images/arrow-left.svg',
  arrowRight:   '/Images/arrow-right.svg',
  rectangle1:   '/Images/Rectangle1.png',
  rectangle4:   '/Images/Rectangle4.png',
  chevronRightDark: '/Images/chevron-right-dark.svg',
} as const;
